Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: spotify-playlist-getter
      VersioningConfiguration:
        Status: Enabled # Enable versioning if needed
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Project
          Value: spotify-playlist-getter
  
  UIS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: spotify-playlist-getter.ui
      VersioningConfiguration:
        Status: Enabled # Enable versioning if needed
      WebsiteConfiguration:
        IndexDocument: index.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Project
          Value: spotify-playlist-getter
          
  UIS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UIS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${UIS3Bucket}/*"

Outputs:
  S3BucketName:
    Description: The domain name of the S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: S3BucketName
  UIS3BucketName:
    Description: The domain name of the UI S3 bucket 
    Value: !Ref UIS3Bucket
    Export:
      Name: UIS3BucketName